using System;
using System.Windows.Markup;
using GsPlugin;

namespace Playnite;

/// <summary>
/// XAML markup extension for localized strings.
/// Usage: Text="{loc:LocalizedString some_key}"
///
/// Extends MarkupExtension directly (rather than LocStringMarkup) so that the
/// WPF XAML compiler can resolve this type at build time without needing to load
/// the full Playnite runtime assembly chain.
/// </summary>
[MarkupExtensionReturnType(typeof(string))]
public class LocalizedString : MarkupExtension {
    private string _key;

    public LocalizedString() { }

    public LocalizedString(string key) {
        _key = key;
    }

    public string Key {
        get => _key;
        set => _key = value;
    }

    public override object ProvideValue(IServiceProvider serviceProvider) {
        if (string.IsNullOrEmpty(_key)) return string.Empty;
        try {
            return Loc.Api?.GetLocalizedString(_key) ?? _key;
        }
        catch {
            return _key;
        }
    }
}

/// <summary>
/// Localization helper. Call Loc.Api = args.Api in InitializeAsync before use.
/// LocId constants and typed Loc methods are auto-generated by:
///   Toolbox.exe ftlgen "Localization/" "Localization/"
/// Run this after adding or renaming keys in en_US.ftl.
/// </summary>
public static partial class Loc {
    public static IPlayniteApi Api = null!;

    public static string GetString(string stringId) =>
        Api?.GetLocalizedString(stringId) ?? stringId;

    public static string GetString(string stringId, params (string name, object value)[] args) =>
        Api?.GetLocalizedString(stringId, args) ?? stringId;

    public static bool IsStringId(string id) {
        return LocId.StringIds.Contains(id);
    }
}
