using GsPlugin;
using Playnite.Markup;

namespace Playnite;

/// <summary>
/// XAML markup extension for localized strings. Usage: Text="{p:LocalizedString {x:Static p:LocId.some_key}}"
/// </summary>
public class LocalizedString : LocStringMarkup {
    public LocalizedString() : base(GsPluginPlugin.Id) {
    }

    public LocalizedString(string stringId) : base(GsPluginPlugin.Id, stringId) {
    }
}

/// <summary>
/// Localization helper. Call Loc.Api = args.Api in InitializeAsync before use.
/// LocId constants and typed Loc methods are auto-generated by:
///   Toolbox.exe ftlgen "Localization/" "Localization/"
/// Run this after adding or renaming keys in en_US.ftl.
/// </summary>
public static partial class Loc {
    public static IPlayniteApi Api = null!;

    public static string GetString(string stringId) {
        return Api.GetLocalizedString(stringId);
    }

    public static string GetString(string stringId, params (string name, object value)[] args) {
        return Api.GetLocalizedString(stringId, args);
    }

    public static bool IsStringId(string id) {
        return LocId.StringIds.Contains(id);
    }
}
